local plugin_list = {
  -- "tpope/vim-abolish",
  "~/Desktop/NeovimPlugins/vim-abolish",
  "wbthomason/packer.nvim",
  "~/Desktop/NeovimPlugins/live-command.nvim",
  "smjonas/live-tests-busted.nvim",
  "~/Desktop/NeovimPlugins/snippet-converter.nvim",
  {
    "nvim-treesitter/nvim-treesitter",
    requires = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "nvim-treesitter/playground",
      module = "nvim-treesitter-textobjects",
    },
  },
  "danymat/neogen",
  { "nvim-lualine/lualine.nvim", requires = "kyazdani42/nvim-web-devicons" },
  -- Color schemes
  "projekt0n/github-nvim-theme",
  "folke/tokyonight.nvim",
  -- LSP
  { "neovim/nvim-lspconfig", requires = "folke/neodev.nvim" },
  "glepnir/lspsaga.nvim",
  "ray-x/lsp_signature.nvim",
  { "jose-elias-alvarez/null-ls.nvim", requires = "nvim-lua/plenary.nvim" },
  { "williamboman/mason.nvim", requires = "williamboman/mason-lspconfig.nvim" },
  "j-hui/fidget.nvim",
  -- "SmiteshP/nvim-navic",
  { "mfussenegger/nvim-dap", requires = "jbyuki/one-small-step-for-vimkind" },
  -- Visual / UX enhancements
  {
    "anuvyklack/windows.nvim",
    requires = {
      "anuvyklack/middleclass",
      "anuvyklack/animation.nvim",
    },
  },
  "~/Desktop/NeovimPlugins/inc-rename.nvim",
  { "folke/noice.nvim", requires = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" } },
  -- Tree viewer / file browser
  { "lambdalisue/fern.vim", requires = "lambdalisue/fern-hijack.vim" },
  -- Auto-completion and snippets
  {
    "hrsh7th/nvim-cmp",
    requires = {
      "saadparwaiz1/cmp_luasnip",
      "max397574/cmp-greek",
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-path",
      "hrsh7th/cmp-nvim-lsp",
    },
  },
  { "L3MON4D3/LuaSnip", requires = "rafamadriz/friendly-snippets" },
  {
    -- "nvim-telescope/telescope.nvim",
    "~/Desktop/NeovimPlugins/telescope.nvim",
    requires = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope-fzf-native.nvim",
      "smartpde/telescope-recent-files",
    },
  },
  -- Filetype-specific plugins
  "mattn/emmet-vim",
  "alvan/vim-closetag",
  "lervag/vimtex",
  "NvChad/nvim-colorizer.lua",
  "vim-test/vim-test",
  -- "wellle/targets.vim",
  "echasnovski/mini.nvim",
  { "Julian/vim-textobj-variable-segment", requires = "kana/vim-textobj-user" },
  "inkarkat/vim-ReplaceWithRegister",
  -- New ways to manipulate text
  "kylechui/nvim-surround",
  "windwp/nvim-autopairs",
  "AndrewRadev/sideways.vim",
  "zirrostig/vim-schlepp",
  {
    "numToStr/Comment.nvim",
    requires = {
      "JoosepAlviste/nvim-ts-context-commentstring",
      "nvim-treesitter/nvim-treesitter",
    },
  },
  "ggandor/leap.nvim",
  "tpope/vim-fugitive",
  { "sindrets/diffview.nvim", requires = "nvim-lua/plenary.nvim" },
  "vimwiki/vimwiki",
  "iamcco/markdown-preview.nvim",
  -- Misc
  "glacambre/firenvim",
  "luukvbaal/stabilize.nvim",
  "dstein64/vim-startuptime",
  "arp242/undofile_warn.vim",
  "tpope/vim-repeat",
  "lewis6991/impatient.nvim",
  "rmagatti/auto-session",
}

-- "plenary.nvim",
-- "packer.nvim",
local disabled_plugins = {
  -- "Comment.nvim",
  -- "dressing.nvim",
  -- "auto-session",
  -- "diffview.nvim",
  -- "emmet-vim",
  -- "fern-hijack.vim",
  -- "fern.vim",
  -- "fidget.nvim",
  -- "firenvim",
  -- "friendly-snippets",
  "github-nvim-theme",
  -- "impatient.nvim",
  -- "inc-rename.nvim",
  -- "leap.nvim",
  -- "live-command.nvim",
  -- "live-tests-busted.nvim",
  -- "lsp_signature.nvim",
  "lspsaga.nvim",
  -- "neodev.nvim",
  -- "LuaSnip",
  -- "lualine.nvim",
  -- "markdown-preview.nvim",
  -- "mason-lspconfig.nvim",
  -- "mason.nvim",
  -- "neogen",
  -- "null-ls.nvim",
  -- "nvim-autopairs"math.max(0, #updated_lines - #cached_lines) ]],
  -- "nvim-cmp",
  -- "cmp_luasnip",
  -- "cmp-greek",
  -- "cmp-buffer",
  -- "cmp-path",
  -- "cmp-nvim-lsp",
  "nvim-colorizer.lua",
  -- "nvim-dap",
  -- "nvim-lspconfig",
  "nvim-navic",
  -- "nvim-treesitter",
  -- "playground",
  "noice.nvim",
  -- "nvim-treesitter-textobjects",
  -- "nvim-ts-context-commentstring",
  -- "nvim-surround",
  -- "nvim-web-devicons",
  -- "one-small-step-for-vimkind",
  -- "plenary.nvim",
  -- "sideways.vim",
  -- "snippet-converter.nvim",
  -- "stabilize.nvim",
  -- "targets.vim",
  -- "telescope.nvim",
  -- "telescope-fzf-native.nvim",
  -- "telescope-recent-files",
  -- "tokyonight.nvim",
  -- "undofile_warn.vim",
  -- "vim-ReplaceWithRegister",
  -- "vim-closetag",
  -- "vim-fugitive",
  -- "vim-repeat",
  -- "vim-schlepp",
  -- "vim-startuptime",
  -- "vim-test",
  -- "vim-textobj-user",
  -- "vim-textobj-variable-segment",
  -- "vimtex",
}

return {
  all = plugin_list,
  disabled = disabled_plugins,
}
